# Generated by Django 3.2.5 on 2021-07-31 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published_date',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='published_date',
        ),
    ]
